### PR TITLE
Set basic authentication globally

### PR DESCRIPTION
**Pull request by mightyfrog**

### CODE REVIEW

**Comment by koush** [comment]
This is super sketchy, as then your basic auth can accidentally go to services other than the ones you mean. if you're using ion to download images from one webserver, and json to another, this is not good.

I'd recommend implementing a middleware to handle this.

**Comment by koush** [comment]
Basically, there needs to be a way to do per server default authorization.

**Comment by mightyfrog** [comment]
You're right. I was totally oblivious to per server configuration because we only use a single domain. I make this change every time I update Ion so we can use it in staging environments. Anyway I've made changes so it checks the domain just in case. It would be good if Ion has some easier way to handle basic authentication. Ion code is everywhere so it's not feasible to have everything in if clauses.

Can you point me to middleware examples?

**Comment by koush** [comment]
shit i get this question a lot and i suck at documentation. Let me do a quick sample and push it.

**Comment by koush** [comment]
here you go

https://github.com/koush/AndroidAsync/blob/master/AndroidAsyncSample/src/com/koushikdutta/async/sample/middleware/BasicAuthMiddleware.java

**Comment by mightyfrog** [comment]
On 2/16/2015 04:00, Koushik Dutta wrote:
>
> here you go
>
> https://github.com/koush/AndroidAsync/blob/master/AndroidAsyncSample/src/com/koushikdutta/async/sample/middleware/BasicAuthMiddleware.java
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/koush/ion/pull/480#issuecomment-74431112>.
>
Thanks. It works perfectly.


---
This email has been checked for viruses by Avast antivirus software.
http://www.avast.com

**Pull request closed without merging**
